name: build_front_end

on:
  workflow_dispatch:
  pull_request:
    paths:
      - server-redis/**
  push:
    paths:
      - server-redis/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server-redis
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm install
      - run: npm run build
